id: A8AC4190F
title: 'The Rain of Enlightened Activity: A Prayer to the Gurus of the Lineage of
  the Vital Essence of the Aural Transmission Kīla'
type: translation
pechas:
- I78798777
- IA10A0B6E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:36:56.234831
  last_modified_at: 2023-01-04 11:36:56.234845
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I78798777/4F26: 7C7C
  IA10A0B6E/8E73: 7C7C
